In [23]:
import numpy as np

1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]

In [4]:
import os
import hashlib

def find_duplicates(root):
    hashes = {}
    duplicates = []
    for dirpath, dirnames, filenames in os.walk(root):
        for filename in filenames:
            full_path = os.path.join(dirpath, filename)
            with open(full_path, 'rb') as file:
                file_hash = hashlib.sha256(file.read()).hexdigest()
            if file_hash in hashes:
                duplicates.append(full_path)
            else:
                hashes[file_hash] = full_path
    return duplicates

def delete_duplicates(duplicates):
    for path in duplicates:
        os.remove(path)
        
path=input("Enter The Path : ")
dup=find_duplicates(path)
for i in dup:
    print(i)
    
deleted_dups=delete_duplicates(dup)
print("The deleted files are",deleted_dups)

Enter The Path : C:/Users/pmundrai/tekpython
C:/Users/pmundrai/tekpython\test2.txt
The deleted files are None


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.

In [1]:
import string
import random
length=17
upper=string.ascii_uppercase
lower=string.ascii_lowercase
digits=string.digits
spl_char=string.punctuation
all=upper+lower+digits
password=''
password=random.sample(all,length-2)
for i in range(2):
    password.append(random.choice(spl_char))
random.shuffle(password)
password=''.join(password)
print("THE PASSWORD IS :",password)

THE PASSWORD IS : irFW:0NmRadDMX4G)


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [53]:

def check(n):
    if n<2:
        return 0;
    for i in range(2,n//2+1):
        if n%i==0:
            return 0;
    return n*n*n;
a1=np.arange(0,50).reshape(5,10)
li=l=a1.flatten().tolist()
for i in li:
    if check(i)!=0:
        li[i]=check(i)
sol=np.array(li).reshape(5,10)
sol

array([[     0,      1,      8,     27,      4,    125,      6,    343,
             8,      9],
       [    10,   1331,     12,   2197,     14,     15,     16,   4913,
            18,   6859],
       [    20,     21,     22,  12167,     24,     25,     26,     27,
            28,  24389],
       [    30,  29791,     32,     33,     34,     35,     36,  50653,
            38,     39],
       [    40,  68921,     42,  79507,     44,     45,     46, 103823,
            48,     49]])

4.	Python program to get the sum of every cubed value and its previous integer. 

In [69]:
def check(n):
    if n<2:
        return 0;
    for i in range(2,n//2+1):
        if n%i==0:
            return 0;
    return 1;
a1=np.arange(0,50).reshape(5,10)
li=l=a1.flatten().tolist()
t=0
for i in li:
    if check(i)!=0:
        t=(i-1)*(i-1)*(i-1) if check(i-1) else i-1
        li[i]=i*i*i + t
sol=np.array(li).reshape(5,10)
sol

array([[     0,      1,      9,     35,      4,    129,      6,    349,
             8,      9],
       [    10,   1341,     12,   2209,     14,     15,     16,   4929,
            18,   6877],
       [    20,     21,     22,  12189,     24,     25,     26,     27,
            28,  24417],
       [    30,  29821,     32,     33,     34,     35,     36,  50689,
            38,     39],
       [    40,  68961,     42,  79549,     44,     45,     46, 103869,
            48,     49]])

5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]

arr2[] = [2, 3, 5, 6]


In [107]:
a = [1, 3, 4, 5, 7]
b = [2, 3, 5, 6]
a=list(set(a).intersection(b))
a

[3, 5]

6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [25]:
import numpy as np
n=7*7
ar=np.arange(7,n*7+1,7).reshape(7,7)
print(ar)
ar[-1][-1]

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]


343

7.	Checker Board Patten using Numpy:




In [75]:
x=np.zeros((8,8),dtype='int')
x[1::2, 1::2] = 1
x[::2, 0::2] = 1
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

8.	Create a given Matrix:

[  A,     B,     C,       D

E,      F,     G,       H

I,      a,      K,       L

M,    N,     o,       P

Q,     R,      S,       T

U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [104]:
import numpy as np
a2=np.array([['A','B','C','D'],
             ['E','F','G','H'],
            ['I','J','K','L'],
             ['M','N','O','P'],
            ['Q','R','S','T'],
             ['U','V','W','X']])
a1=a2
l=a1.flatten().tolist()
vow=['A','E','I','O','U']
for i in range(len(vow)):
    vow[i]=l.index(vow[i])
for i in vow:
    l[i]=np.nan
sol_arr=np.array(l)
sol_arr=sol_arr.reshape(4,6)
sol_arr
count=0
for i in sol_arr:
    k=len(i)
    for j in range(k):
        if i[j]=='nan':
            count+=1
count

5